### ISSUE TITLE
hook

### ISSUE THREAD

**Issue by ddkwork** [tandasat/recon2024_demo#1]
Hi, I have a thought to verify this, not sure if it will trigger the kernel pg protection causing bsod:.

1 Find the ntbase address through debugging
2 Parse pe and disassemble to get the rva of ntcreateFile.
3 base +rva = ntcreatFile's physical memory address, at this time the organization of inlinehook code: apply for memory, jmp function header, print the call, make up the missing bytes, return to the address behind the patch, etc. to complete the api hook operation.

Does hook nt api in this mode trigger pg to bsod?

**Comment by ddkwork** [comment]
Theoretically this process takes three steps

Implementing write memory commands to two addresses and requesting non-paged memory operations in kernel mode using the repository's implementation

**Comment by tandasat** [comment]
it would
